### PR TITLE
created juila programme that converts radian to degree

### LINKED ISSUE #1176: Radian to degree
### Description

Write a programme to convert radian to degree

1Deg × π/180 = 0.01745Rad

```
Input  : 1
Output : 57.2958
```

### Tracking Issues

- [x] #1177
- [x] #1178
- [x] #1179
- [x] #1180
- [x] #1181
- [x] #1182
- [x] #1183
- [x] #1184
- [x] #1185

### LINKED ISSUE #1185: Write a Julia programme to convert radian to degree
### Description

Write a programme to convert radian to degree

1Deg × π/180 = 0.01745Rad

```
Input  : 1
Output : 57.2958
```

### PR DESCRIPTION
**Pull request by Adarsh-jaiss**
Write a programme to convert radian to degree.

### Why:

Closes #1185

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Please do 3 things below:

- replace current comment with `# Write a programme to convert radian to degree`
- write 2 lines that will print input and output
- add your name to contributor list in the `README.md` file under this folder

Thank you, @Adarsh-jaiss!

**Comment by Adarsh-jaiss** [comment]
> Please do 3 things below:
> 
>     * replace current comment with `# Write a programme to convert radian to degree`
> 
>     * write 2 lines that will print input and output
> 
>     * add your name to contributor list in the `README.md` file under this folder
> 
> 
> Thank you, @Adarsh-jaiss!

-- All changes have been successfully done :)
-- kindly review it once again

**Review by victoriacheng15 — DISMISSED** [review]
In general, we would like to have the users to give a value and then the code will print the answer after. e.g. if value is `1`, the answer should be `57.29577951308232`.  Or if value is `8`, the answer should be `458.3662361046586`. 


The format looks like this below, and please keep `# Write a program to convert Radian to Degree`.
```jl
# Write a program to convert Radian to Degree

# your code that ask for a value and then print answer after
```
Please refer to more julia files to see the code format.

If I am not clear, please do let me know as well.

Thank you, @Adarsh-jaiss!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by harshraj8843** [comment]
> In general, we would like to have the users to give a value and then the code will print the answer after. e.g. if value is `1`, the answer should be `57.29577951308232`. Or if value is `8`, the answer should be `458.3662361046586`.
> 
> The format looks like this below, and please keep `# Write a program to convert Radian to Degree`.
> 
> ```julia
> # Write a program to convert Radian to Degree
> 
> # your code that ask for a value and then print answer after
> ```
> 
> Please refer to more julia files to see the code format.
> 
> If I am not clear, please do let me know as well.
> 
> Thank you, @Adarsh-jaiss!

Thanks for the review 👍🏻

**Pull request merged**
