### PR TITLE
Added Volume of Cuboid programs for C, Cpp, Python and Updated Readme file.

### LINKED ISSUE #1003: Write a C programme to find volume of a cuboid
```
Length : 2
Width  : 3
Height : 4

Volume : 24
```

### LINKED ISSUE #1004: Write a C++ programme to find volume of a cuboid
```
Length : 2
Width  : 3
Height : 4

Volume : 24
```

### LINKED ISSUE #1007: Write a Python programme to find volume of a cuboid
```
Length : 2
Width  : 3
Height : 4

Volume : 24
```

### PR DESCRIPTION
**Pull request by Harshvardhantomar**
### Why:

Closes #1007 
Closes #1003  
Closes #1004 

### What's being changed:
Added Volume of Cuboid programs for C, Cpp, Python

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by saniketmore — COMMENTED** [review]
LGTM but some nit comments:
1. it would be better if you write a function (say calculate_vol) in all 3 files - just a good practice
2. you should keep naming of variables consistent, for example if using small case for length, breadth, etc, then should also use the same for volume - this is really trivial I know, but I have OCD, so pointed it out!

**Comment by Harshvardhantomar** [comment]
So should I edit the programs or should I make sure to do this next time?

**Comment by harshraj8843** [comment]
> LGTM but some nit comments:
> 
> 1. it would be better if you write a function (say calculate_vol) in all 3 files - just a good practice
> 2. you should keep naming of variables consistent, for example if using small case for length, breadth, etc, then should also use the same for volume - this is really trivial I know, but I have OCD, so pointed it out!

Thanks @saniketmore for the review 👍🏻

**Comment by harshraj8843** [comment]
> So should I edit the programs or should I make sure to do this next time?

I have edited the programmes, you can check if anything can be improved 😄

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
