### PR TITLE
add radian-to-degree.php

### LINKED ISSUE #1184: Write a PHP programme to convert radian to degree
### Description

Write a programme to convert radian to degree

1Deg × π/180 = 0.01745Rad

```
Input  : 1
Output : 57.2958
```

### PR DESCRIPTION
**Pull request by JefvdA**
### Why:

Closes #1184 

### What's being changed:
- Added programme that converts radian to degree

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by victoriacheng15 — CHANGES_REQUESTED** [review]
Can you please do the 2 things below?

- Add `Write a programme to convert radian to degree` comment inside the code block
- Add your name to the contributor list in the README

Thank you for contributing, @JefvdA!

**Comment by JefvdA** [comment]
I added the comment inside the programme.
Also added myself to the contributors list in the README 👍

**Review by victoriacheng15 — APPROVED** [review]
Awesome, thank you for made changes! 

They look good!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Pull request merged**
