### PR TITLE
Python issue

### LINKED ISSUE #1061: Write a Python programme to find sum of n numbers
### Description

Write a programme to find sum of n numbers

```
Input  : 1 2 3 4
Output : 10
```

### LINKED ISSUE #1071: Write a Python programme to convert lowercase string to uppercase
### Description

Write a programme to convert lowercase string to uppercase

```
Input  : hii there
Output : HII THERE
```

### LINKED ISSUE #1081: Write a Python programme to convert uppercase string to lowercase
### Description

Write a programme to convert uppercase string to lowercase

```
Input  : HII THERE
Output : hii there
```

### LINKED ISSUE #1091: Write a Python programme to find square root of a number
### Description

Write a programme to find square root of a number

```
Input  : 25
Output : 5
```

### LINKED ISSUE #1101: Write a Python programme to generate a random number in range n1, n2
### Description

Write a programme to generate a random number in range n1, n2

```
Start range : 0
End   range : 100

Output : 27
```

### LINKED ISSUE #1111: Write a Python programme to generate a random even number in range n1-n2
### Description

Write a programme to generate a random even number in range n1-n2

```
Start range : 0
End   range : 100

Output : 44
```

### LINKED ISSUE #1121: Write a Python programme to generate a random odd number in range n1-n2
### Description

Write a programme to generate a random odd number in range n1-n2

```
Start range : 0
End   range : 100

Output : 33
```

### LINKED ISSUE #1131: Write a Python programme to generate a random prime number in range n1-n2
### Description

Write a programme to generate a random prime number in range n1-n2

```
Start range : 0
End   range : 100

Output : 53
```

### LINKED ISSUE #1141: Write a Python programme to find index of an alphabet
### Description

Write a programme to find index of an alphabet

> **Note** index starts from 1

```
Input  : C
Output : 3
```

### LINKED ISSUE #1151: Write a Python programme to check even or odd string
### Description

Write a programme to check even or odd string

```
Input  : hiithere
Output : Even String
```

```
Input  : hii
Output : Odd String
```

### LINKED ISSUE #1161: Write a Python programme to count capital letters in a string
### Description

Write a programme to count capital letters in a string

```
Input  : HiiThere
Output : 2
```

### PR DESCRIPTION
**Pull request by PaoloFer**
### Why:

1. - Closes #1161
2. - Closes #1151
3. - Closes #1141
4. - Closes #1131
5. - Closes #1121
6. - Closes #1111
7. - Closes #1101
8. - Closes #1091
9. - Closes #1081
10. -  Closes #1071
11. -  Closes #1061

### What's being changed:

1. - Add random-prime-number/random-prime-number.py
2. - Add capital-letter-in-string/capital-letter-in-string.py
3. - Add lowercase-to-uppercase/lowercase-to-uppercase.py
4. - Add odd-even-string/odd-even-string.py
5. - Add random-even-number/random-even-number.py
6. - Add random-number/random-number.py
7. - Add random-odd-number/random-odd-number.py
8. - Add square-root/square-root.py
9. - Add sum-of-numbers/sum-of-numbers.py
10. - Add uppercase-to-lowercase/uppercase-to-lowercase.py
11.  - Add index-of-alphabet/index-of-alphabet.py

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by PaoloFer** [comment]
can someone review my pr? Is everything okey or i have to do some changes?

**Comment by PaoloFer** [comment]
Can someone review my pull request? So that i can change the wrong thing

**Review by victoriacheng15 — COMMENTED** [review]
Checked code part, they look good. 

A friendly reminder, READMEs are not added yet for each folder.

Thank you for contributing, @PaoloFer!

**Comment by harshraj8843** [comment]
> Checked code part, they look good.
> 
> A friendly reminder, READMEs are not added yet for each folder.
> 
> Thank you for contributing, @PaoloFer!

Thanks for the review 👍🏻

**Comment by harshraj8843** [comment]
tracked in #1216

**Pull request merged**
