### PR TITLE
Create random-odd-number in C, Capital Letters Counter in Julia, Comvert Lowercase to Uppercase in C

### LINKED ISSUE #1117: Write a C programme to generate a random odd number in range n1-n2
### Description

Write a programme to generate a random odd number in range n1-n2

```
Start range : 0
End   range : 100

Output : 33
```

### PR DESCRIPTION
**Pull request by SpirosArk**
### Why:

Closes #1117 
#1067 
#1165 

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by victoriacheng15 — DISMISSED** [review]
Checked the code and it works for me! 

Also, can you please add your name to the contributor list in the README.md?

Thank you for contributing @SpirosArk!

**Comment by SpirosArk** [comment]
Asked a pull request here: https://github.com/SpirosArk/codinasion-programme/pull/2

**Comment by SpirosArk** [comment]
I think now it's ok

**Review by victoriacheng15 — COMMENTED** [review]
Thank you for added your name to the list! 

Also, I forgot to mention this in the last review.  Can you please add comment  `## Write a programme to generate a random odd number in range n1-n2` to your code? 😅

**Review by SpirosArk — COMMENTED** [review]
Fixes what asked on review

**Review by victoriacheng15 — COMMENTED** [review]
Please add your name to the contributor list and add problem statements for the 2 new files that you just added. 

Thank you, @SpirosArk!

**Comment by SpirosArk** [comment]
I think now it's ready

**Comment by victoriacheng15** [comment]
I just checked README.md and ok, look good to me!

Thank you!

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Pull request merged**
