### PR TITLE
Print Even Numbers

### LINKED ISSUE #138: Print Even Numbers
### Title of article

Write a Java programme to print first n even numbers.

### Additional information

```
Input: 5
Output: 0 2 4 6 8
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### LINKED ISSUE #162: Simple Interest Calculator
### Title of article

Write a Java programme to calculate simple interest.

### Additional information

P : Principle Amount
T : Time Period
R : Rate of Interest

```
Enter P : 5000
Enter T : 10
Enter R : 5

Simple Interest : 2500
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Anzo52**
### Why: Java program to print even numbers

Closes #138 

Closes #162

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
empty function

**Comment by Anzo52** [comment]
@harshraj8843 Sorry, not sure what happened there, it's in now.

**Review by Anzo52 — COMMENTED** [review]
:+1:

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Pull request merged**
