### PR TITLE
 Juila codes from Q1-Q16

### LINKED ISSUE #897: add Julia language
- add `Julia` programmes

### PR DESCRIPTION
**Pull request by SanjayShetty01**
### Why:

Closes #897 

### What's being changed:

The Julia codes for Tutorial from Q.1 to Q.16 have been added. 

The Tutorials added to

- [ ] #943
- [ ] #944
- [ ] #945
- [ ] #916
- [ ] #946
- [ ] #920 
- [ ] #947
- [ ] #948
- [ ] #918 
- [ ] #949
- [ ] #950
- [ ] #951
- [ ] #952
- [ ] #953
- [ ] #954
- [ ] #955

The changes to the corresponding Readme.md has also been done. 

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
👋🏻 Hey @SanjayShetty01 

Thanks for contributing to this project 😃 

This PR will be reviewed and merged shortly 👍🏻

**Comment by PrajwalBorkar** [comment]
@SanjayShetty01  Please resolve the conflicts to merge the PR.

**Comment by harshraj8843** [comment]
> @SanjayShetty01 Please resolve the conflicts to merge the PR.

Those will be resolved while reviewing

Thanks 👍🏻

**Comment by Anzo52** [comment]
Hey @harshraj8843 this'll be my first review... ever, so I'm wondering what that entails and what to look for. Also, I'm a little confused about these conflicts as I haven't come across that kind of situation before. Something about "jl" and "js" getting mixed up? Thanks for your patience!

**Comment by harshraj8843** [comment]
> Hey @harshraj8843 this'll be my first review... ever, so I'm wondering what that entails and what to look for. Also, I'm a little confused about these conflicts as I haven't come across that kind of situation before. Something about "jl" and "js" getting mixed up? Thanks for your patience!

Hey @Anzo52 

Please [consider this for reviewing purpose of any PR](https://github.com/orgs/codinasion/teams/codinasion-programme/discussions/2)

Merge conflicts will be resolved before merge, no worry 😃 

This PR will be reviewed after :
- [ ] creating `Julia` programme issues ( In Progress )
- [ ] linking respective issues to this PR

**Pull request closed without merging**
