### PR TITLE
Add AreaOfRhombus for Kotlin

### PR DESCRIPTION
**Pull request by KikiManjaro**
Add AreaOfRhombus for Kotlin

### CODE REVIEW

**Review by SpirosArk — DISMISSED** [review]

**Review by PrajwalBorkar — DISMISSED** [review]

**Review by PrajwalBorkar — DISMISSED** [review]

**Comment by KikiManjaro** [comment]
@PrajwalBorkar why did you rename files ? We have said here : https://github.com/codinasion/codinasion-programme/issues/1227 that we wanted to use naming convention of the used language, don't you agree ?

@SpirosArk class declaration is present in java file that's why i kept it in kotlin, it was working on IntelliJ Idea, i was thinking we could kept that but not really important

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar why did you rename files ? We have said here : #1227 that we wanted to use naming convention of the used language, don't you agree ?
> 
Sorry, I didn't see that issue. Reverted the changes 👍

**Comment by SpirosArk** [comment]
> @PrajwalBorkar why did you rename files ? We have said here : #1227 that we wanted to use naming convention of the used language, don't you agree ?
> 
> @SpirosArk class declaration is present in java file that's why i kept it in kotlin, it was working on IntelliJ Idea, i was thinking we could kept that but not really important

When the user of the page will get to test the code themselves let's say on his IDE or on any other online compiler he won't be able to compile the program, test it and see if it works. So he would end up with a pseudocode thing. That's why I try to always make the code run on online compilers with only copy and pasting the code.

**Review by SpirosArk — APPROVED** [review]

**Comment by KikiManjaro** [comment]
> > @PrajwalBorkar why did you rename files ? We have said here : #1227 that we wanted to use naming convention of the used language, don't you agree ?
> > @SpirosArk class declaration is present in java file that's why i kept it in kotlin, it was working on IntelliJ Idea, i was thinking we could kept that but not really important
> 
> When the user of the page will get to test the code themselves let's say on his IDE or on any other online compiler he won't be able to compile the program, test it and see if it works. So he would end up with a pseudocode thing. That's why I try to always make the code run on online compilers with only copy and pasting the code.

Ok :) seems legit

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Pull request merged**
