### PR TITLE
 Update even-or-odd.py

### LINKED ISSUE #764: Even or Odd
### Title of programme

Write a Python programme to check a number even or odd.

### Additional information

```
Input  : 3
Output : Odd Number
```

```
Input  : 2
Output : Even Number
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-programme/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Stevie011**
### Why:

Closes #764 

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ ] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by PrajwalBorkar — COMMENTED** [review]
Great work. Also, make sure to update the readme.md file

**Comment by Stevie011** [comment]
thanks so much for creating this to help us learn

**Comment by harshraj8843** [comment]
> thanks so much for creating this to help us learn

Hey @Stevie011 

Thanks for contributing to this project 👍🏻 

We could really update that code 🤗 

Would you like to reopen this PR

**Comment by Stevie011** [comment]
so sorry for closing the pr unduly!

**Review by harshraj8843 — APPROVED** [review]
Thank for contributing 👍🏻

**Pull request merged**
