### PR TITLE
Java average

### LINKED ISSUE #126: Average of Numbers
### Title of article

Write a Java programme to calculate the average of numbers.

### Additional information

```
Input:  2 3 4
Output: 3
```

```
Input: 1 2 3 4 5
Output: 3
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### LINKED ISSUE #531: Name of class must match filename
### What would you like to share?

https://github.com/codinasion/codinasion-programme/blob/6fb2c99d4720f9fca06ddd57acca96059a4ad2d5/programme/years-to-days/years-to-days.java#L4

this line must be changed to:

`public class years-to-days {`

### Additional information

I can fix and do a PR if needed.

### PR DESCRIPTION
**Pull request by Anzo52**
### Why: average-of-numbers

Closes #126
Closes #531 

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by Anzo52 — COMMENTED** [review]
:+1:

**Comment by Anzo52** [comment]
Well...I didn't mean to have all that in the same PR...

**Comment by harshraj8843** [comment]
Hey @Anzo52 

Thanks for this PR, really great work  👍🏻 

This PR will be reviewed and merged shortly.

**Review by harshraj8843 — APPROVED** [review]
Thanks :)

**Pull request merged**
