### PR TITLE
Digital Root Added

### LINKED ISSUE #664: Digital Root
### Title of programme

Write a C programme for Digital Root of a number

`Digital Root` is the single number obtained by adding the number successively.

```
347 = 3 + 4 + 7 = 14
14 = 1 + 4 = 5
```

Thus, 5 is a single digit number, which is the digital root/ seed number of 347.

### Additional information

```
Input  : 347
Output : 5
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-programme/blob/master/CODE_OF_CONDUCT.md)

### LINKED ISSUE #665: Digital Root
### Title of programme

Write a C++ programme for Digital Root of a number

`Digital Root` is the single number obtained by adding the number successively.

```
347 = 3 + 4 + 7 = 14
14 = 1 + 4 = 5
```

Thus, 5 is a single digit number, which is the digital root/ seed number of 347.

### Additional information

```
Input  : 347
Output : 5
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-programme/blob/master/CODE_OF_CONDUCT.md)

### LINKED ISSUE #668: Digital Root
### Title of programme

Write a Python programme for Digital Root of a number

`Digital Root` is the single number obtained by adding the number successively.

```
347 = 3 + 4 + 7 = 14
14 = 1 + 4 = 5
```

Thus, 5 is a single digit number, which is the digital root/ seed number of 347.

### Additional information

```
Input  : 347
Output : 5
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-programme/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by user-64bit**
### Why:

Closes #664 

Closes #665 

Closes #668 

### What's being changed:
I've added Digital Root Folder which have digital_root.c,digital_root.cpp and digital_root.py.
### Check off the following:

- [X] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion-programme/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @arth2002 

Thanks for contributing to this project 😃 

This PR will be reviewed and merged shortly

**Comment by arth2002** [comment]
> Hey @arth2002
> 
> Thanks for contributing to this project smiley
> 
> This PR will be reviewed and merged shortly

@harshraj8843 hey bro what to do next?
and what is the meaning of awaiting triage?

**Comment by harshraj8843** [comment]
> @harshraj8843 hey bro what to do next? and what is the meaning of awaiting triage?

Hey @arth2002 

This PR will be reviewed soon

The issue for this PR is not yet available, so first the issue will be raised then only it can be merged

**Comment by arth2002** [comment]
@harshraj8843 
so until someone raises the issue nothing can be done?
what if I raise issue?

**Comment by harshraj8843** [comment]
> @harshraj8843 so until someone raises the issue nothing can be done? what if I raise issue?

I am raising issue for this 👍🏻

**Comment by arth2002** [comment]
@harshraj8843 Thank you

**Comment by harshraj8843** [comment]
Hey @arth2002 

Please move files from `programme/Digital Root/` to `programme/digital-root/` folder

Thanks 👍🏻

**Comment by arth2002** [comment]
@harshraj8843  Done

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by arth2002** [comment]
Hey @harshraj8843 
I have one doubt, why my name is not showing in the contributers section?

**Comment by harshraj8843** [comment]
Hey @arth2002 

No idea about [homepage contributors](https://github.com/codinasion/codinasion-programme/graphs/contributors) exactly

But its showing in [file contributors](https://github.com/codinasion/codinasion-programme/blob/master/programme/digital-root/digital_root.c)

Screenshot from 2022-05-25 13-18-05


Maybe [this will fix it](https://stackoverflow.com/a/43527384)

**Comment by arth2002** [comment]
Thanks
it is showing in github mobile app

**Pull request merged**
