### PR TITLE
Name fixing

### PR DESCRIPTION
**Pull request by SpirosArk**
### Why:
Noticed some name inconsistencies in some folders and tried to fix manually some of them, might fix more if I find time or I may write a script to do so by file extension
### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by harshraj8843 — COMMENTED** [review]
This PR needs some discussion in #1227

**Comment by harshraj8843** [comment]
Hey @SpirosArk @PrajwalBorkar @victoriacheng15 

Please check your emails ✉️

**Comment by SpirosArk** [comment]
Done @harshraj8843 !

**Comment by PrajwalBorkar** [comment]
The changes u mentioned gonna improve org so go ahead with that 🎉. Also which repos will be archived 🤔 do will still approve prs or it is automated?

**Comment by harshraj8843** [comment]
> which repos will be archived

`codinasion-programme` and `codinasion-dsa` will be most affected

---

> do will still approve prs or it is automated

the PR will still be approved manually, but only the code will be reviewed. There will be no `README` or `folder` issue

---

## Some major changes :-

- new repo will be named `program` instead of `programme` (it confuses many contributors)
- now PR(s) will be merged on an `assignment basis` (first contributors will `auto assign` the respective issue, then they will raise PR) (same issue conflict will be very common in `Hacktoberfest`)
- `program` and `dsa` repos will be treated as good-first-repos. so, from now onward a contributor can contribute to 5 issues maximum in each repo. It will give everyone a chance to contribute
- there will be no requirement to update `README`(s) and `folder`(s). Github action will take care of it.
- good first issues will be tweeted to `Twitter` to help other contributors find new good first issues

**Comment by SpirosArk** [comment]
So after the 5 contributions, how is one can contribute?

**Comment by harshraj8843** [comment]
> So after the 5 contributions, how is one can contribute?

they can contribute to other repos

These limits will be removed after `Hacktoberfest`

**Comment by PrajwalBorkar** [comment]
> * there will be no requirement to update `README`(s) and `folder`(s). Github action will take care of it.

Thats great I also wanted to know how to create these github actions 👀
> * good first issues will be tweeted to `Twitter` to help other contributors find new good first issues

 Yeah twitter bot is great for good first issues it will increase interaction in community 👍 Eddie also have one https://github.com/EddieHubCommunity/good-first-issue-finder

We can follow eddiehub for more such ideas.

**Pull request closed without merging**
