### PR TITLE
Create area-of-rhombus.js

### LINKED ISSUE #505: Area of a rhombus
### Title of article

Write a program to compute area of Rhombus

- Takes the length of **two diagonals**
- Uses the formula to calculate the area
- Return the value

Area of a rhombus = ( ` diagonal 1 ` * ` diagonal 2 ` ) / 2

#### Example:

Diagonal 1 = 6, Diagonal 2 = 8

Area of the rhombus = (6*8)/2 = 24

#### Programme

```
Diagonal 1 : 6
Diagonal 2 : 8

Area : 24
```

### Tracking Issues

- [x] #508 
- [x] #509 
- [x] #510 
- [x] #511 
- [x] #512 
- [x] #733
- [x] #734

### LINKED ISSUE #733: Area of a rhombus
### Title of programme

Write a JavaScript program to compute area of Rhombus

- Takes the length of **two diagonals**
- Uses the formula to calculate the area
- Return the value

Area of a rhombus = ( ` diagonal 1 ` * ` diagonal 2 ` ) / 2

### Example:

Diagonal 1 = 6, Diagonal 2 = 8

Area of the rhombus = (6*8)/2 = 24

### Programme

```
Diagonal 1 : 6
Diagonal 2 : 8

Area : 24
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion-programme/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by PhysicsMD**
### Why: Added basic rhombus js solution

Closes #733 

### Check off the following:

- [X] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [X] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @PhysicsMD 

Thanks for contributing to this project 😃 

This PR will be reviewed and merged shortly 🚀

**Comment by PhysicsMD** [comment]
@harshraj8843 I would like to help but I wanted to submit one and then do more once I know what you would like, seems like the coding styles are different.

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by harshraj8843** [comment]
>@harshraj8843 I would like to help but I wanted to submit one and then do more once I know what you would like, seems like the coding styles are different.

Hey @PhysicsMD 

Is there anything we can improve in this project 😃

**Pull request merged**
