### PR TITLE
Cpp divide two numbers

### LINKED ISSUE #337: Divide two numbers
### Title of article

Write a C++ programme to divide two numbers.

### Additional information

```
Input  : 4 2
Output : 2
```

```
Input  : 2 4
Output : 0.5
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by akhil484**
### Solved an Issue which was mentioned in the issue page:

Closes #337

### Check off the following:

- [Done ] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [ Done] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion-programme/blob/master/contributing/self-review.md).

### CODE REVIEW

**Comment by harshraj8843** [comment]
Hey @akhil484 

Thanks for contributing to this project 😃

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Comment by akhil484** [comment]
Hey @harshraj8843. I wanted to ask that with the code file am I supposed to update the readme file also?

**Comment by harshraj8843** [comment]
> Hey @harshraj8843. I wanted to ask that with the code file am I supposed to update the readme file also?

Not necessarily

But will appreciate, if you do so (required to update web page)

https://codinasion.vercel.app/programme/divide-two-numbers

**Comment by akhil484** [comment]
Okay, thanks.

**Pull request merged**
