### PR TITLE
Seraph branch

### LINKED ISSUE #1094: Write a PHP programme to find square root of a number
### Description

Write a programme to find square root of a number

```
Input  : 25
Output : 5
```

### LINKED ISSUE #1237: Even or Odd PHP
Write a programme to check a number even or odd.

### Programme

```
Input  : 3
Output : Odd Number
```

### PR DESCRIPTION
**Pull request by seraph776**
### Why:

Closes #1094 
Closes #1237 

### What's being changed:
- Added `square-of-number.php`
- Updated `Read.md` contributor file

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by harshraj8843 — CHANGES_REQUESTED** [review]
Please rename `square-of-number.php` to `square-root-of-number.php` and move `square-root-of-number.php` from folder `square-of-number` to `square-root-of-number`

> **Note** If `square-root-of-number` is not available in your fork, please update your fork

Thanks 👍🏻

**Comment by seraph776** [comment]
@harshraj8843 All files in the directory are named `square-of-number` format. My fork is updated and in sync with yours (screenshot below):

**YOURS**:
image

**MINE**:
image
- Of course mine has the new php file

Do you still want me to rename it?

**Comment by harshraj8843** [comment]
Hey @seraph776 

This is the folders of this repo 

Screenshot from 2022-07-19 08-29-50

And this is the folders of your fork

Screenshot from 2022-07-19 08-30-09

---

> **Note** Notice the `square-root-of-number` folder

---

`square-of-number` folder is for finding square of a number

```
Input  : 5
Output : 25
```

`square-root-of-number` folder is for finding square root of a number

```
Input  : 25
Output : 5
```

---

> **Note** If your fork is updated, maybe your branch `seraph-branch` id not updated with your `master` branch

---

**Comment by seraph776** [comment]
Perhaps I have the wrong repo?

**Pull request closed without merging**
