### PR TITLE
Volume of Sphere

### LINKED ISSUE #1041: Write a Python programme to find volume of cone
### Description

Write a programme to find volume of cone

Volume of cone = 1/3 * π * (radius)^2 * height

```
radius : 2
height : 3

volume : 12.56637
```

### PR DESCRIPTION
**Pull request by seraph776**
### Why: 

- Write a programme to find volume of cone
 
Closes #1041 

### What's being changed:
- Added `volume_of_cone.py`, and `README.md` to `volume-of-cone` directory, and updated the `README.md` file for the main `programme` directory.  

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by NeelPatel31 — DISMISSED** [review]
This code is for 'volume of cone' but code of 'volume of sphere' is needed.

**Comment by seraph776** [comment]
I apologize, my code submission was for #1041

**Review by seraph776 — COMMENTED** [review]
Changes DocString.

**Review by harshraj8843 — APPROVED** [review]
👍🏻

**Pull request merged**
