### PR TITLE
Cube of number JS & C

### LINKED ISSUE #975: Write a C programme to find cube of a number
```
Input  : 2
Output : 8
```

### LINKED ISSUE #981: Write a JavaScript programme to find cube of a number
```
Input  : 2
Output : 8
```

### PR DESCRIPTION
**Pull request by danyroza**
### Why:

Closes #975 
Closes #981 

### What's being changed:

Added JS and C solution for cube of number.
1. programme\cube-of-number\cube-of-numbers.js
2. programme\cube-of-number\cube-of-number.c

### Check off the following:

- [x] I have reviewed my changes in staging (look for "Automatically generated comment" and click **Modified** to view your latest changes).
- [x] For content changes, I have completed the [self-review checklist](https://github.com/codinasion/codinasion/blob/master/contributing/self-review.md).

### CODE REVIEW

**Review by victoriacheng15 — DISMISSED** [review]
In the JS file, I noticed that you used `avgOfnumbers` instead of `cube` for function name. Can you please change the function name? Thank you, @danyroza!

**Comment by danyroza** [comment]
Should be ok now. You've got some great pair of eyes 👍

**Review by victoriacheng15 — COMMENTED** [review]
Awesome, thank you for fast edit! They look good to me!

**Review by harshraj8843 — APPROVED** [review]
Thanks for contributing 👍🏻

**Comment by harshraj8843** [comment]
> Awesome, thank you for fast edit! They look good to me!

Thanks for the review 👍🏻

**Pull request merged**
